#!/bin/sh
# ==========================================
# SSL Deploy Install Script
# ==========================================
# This script will install the dependencies, 
# the SSL Deploy App and the SSL Deploy Service
# on your system. It will also request a license key
# and support pin from Propstat.

# ==========================================
# Helper Scripts
# ==========================================
. ./helpers/confirm_continue.sh
. ./helpers/install_linux_dependencies.sh
. ./helpers/license_request.sh
. ./helpers/mode_selector.sh
. ./helpers/host_certificate_credentials.sh
. ./helpers/host_certificate.sh
. ./helpers/openbao_install.sh

# ==========================================
# Requirement Variables
# ==========================================
RHEL_REQ_VERSION_ID="10"
RHEL_REQ_VERSION_CODENAME="Coughlan"
UBUNTU_REQ_VERSION_ID="26.04"
UBUNTU__REQ_VERSION_CODENAME="Resolute Raccoon"
DEBIAN_REQ_VERSION_ID="13"
DEBIAN_REQ_VERSION_CODENAME="TRIXIE"
ID="undefined"
VERSION_ID="undefined"

# ==========================================
# Installer Variables
# ==========================================
RED=$(printf '\033[0;31m')
NC=$(printf '\033[0m')
ENV_FILE="../.env"


# ==========================================
# Copyright & License Acceptance
# ==========================================

cat << "EOF"

=========================================================
License Agreement
=========================================================

Non-Commercial use is free of charge, please consult our
license for commercial use. The license is available at
https://github.com/propstat/ssldeploy

EOF

year=$(date +%Y)

if [ "$year" -eq 2026 ]; then
    cat <<EOF
=========================================================
© 2026 Propstat
=========================================================
EOF
else
    cat <<EOF
=========================================================
© 2026-$year Propstat
=========================================================
EOF
fi

confirm_continue -n \
    -startmsg="Do you accept the License Agreement?" \
    -endmsg="You have accepted the license agreement." \
    on_no="echo 'You have not accepted the license agreement, the installation is cancelled.'; exit 1" \
    on_yes="echo 'Thank you for accepting the license agreement, proceeding with installation...'"

cat << "EOF"

=========================================================
Privacy Agreement & Data Collected
=========================================================

PROPSTAT will collect some information a unique license key
to request a support pin for your installation from our
servers. The information will also be used for support and
troubleshooting purposes.

The following information will be collected:
- a unique system ID (UUID) generated by this script;
- a timestamp of the installation;
- your IP address.

Please consult our website for the full privacy policy:
https://propstat.org/privacy

=========================================================

EOF

confirm_continue -n \
    -startmsg="Do you accept the Privacy Agreement?" \
    -endmsg="You have accepted the privacy agreement." \
    on_yes="echo 'You have accepted the privacy agreement, proceeding with installation.'" \
    on_no="echo 'You have not accepted the privacy agreement, the installation is cancelled.'; exit 1"

# ==========================================
# Select Mode and Write to .env
# ==========================================

cat << "EOF"

=========================================================
Development (default) or Production Mode
=========================================================

[y/Y] Development Mode (default choice) is meant for testing
      and development purposes. It uses the built-in Flask
      development server and includes the tailwind-cli.
      It is not recommended for production use. Certificates 
      will be generated using Let's Encrypt Staging servers.

[n/N] Production Mode is meant for production use. It uses
      gunicorn as the WSGI server and includes NGINX and
      hardened firewall rules. Certificates will be generated
      using Let's Encrypt Production servers.
    
=========================================================

EOF

confirm_continue -y \
    -startmsg="Do you want to enable Development Mode?" \
    -endmsg="Your selection has been written to the .env file." \
    on_no="ssldeploymode='production'; mode_selector" \
    on_yes="ssldeploymode='development'; mode_selector"

# ==========================================
# Install Dependencies
# ==========================================

cat << "EOF"

=========================================================
Installing Dependencies for SSLDeploy
=========================================================

The direct Linux Dependencies will now be installed.
You will be asked later if you prefer to run SSLDeploy
in any of the following two modes: 

Development     Using the built-in Flask development
                server (not recommended for production)
                including the tailwind-cli

Production      Including NGINX and hardened Firewall rules
                using gunicorn as the WSGI server
                (recommended for production)

Following packages will be alway installed:

- python3
- python3-pip
- python3-venv
- python3-dev
- libffi-dev
- libssl-dev
- build-essential
- libc-bin
- sqlite3
- certbot
- LEGO binaries

Following Packages are only installed for development:

- tailwind-cli

Following Packages are only installed for production:

- gunicorn
- nginx

The respective licenses can be found in the documentation
folder.

=========================================================

EOF

install_linux_dependencies
license_request # Requires SSH, therefor happening after dependencies are installed.

cat << "EOF"

=========================================================
Secret Key Generation
=========================================================

The script will now generate a 256 bit secret key for the
Flask Application. This key is used for session management
and should be kept secret. The key will be stored in the
.env file in the root directory of the application. 

=========================================================

EOF

# Generate new key (256-bit)
SECRET_KEY=$(openssl rand -hex 32)

# Ensure file exists
[ -f "$ENV_FILE" ] || : > "$ENV_FILE"

# Remove existing SECRET_KEY line if present
# (portable approach without sed -i differences)
tmp_file=$(mktemp) || exit 1
grep -v '^SECRET_KEY=' "$ENV_FILE" > "$tmp_file" 2>/dev/null || true

# Write cleaned content back
cat "$tmp_file" > "$ENV_FILE"
rm -f "$tmp_file"

# Append new key using printf
printf 'SECRET_KEY=%s\n' "$SECRET_KEY" >> "$ENV_FILE"

# Optional: output confirmation (without exposing full key)
printf 'New SECRET_KEY generated and written to %s\n' "$ENV_FILE"

unset SECRET_KEY tmp_file

cat << 'EOF'

=========================================================
OpenBao Configuration
=========================================================

ssldeploy stores DNS provider credentials in OpenBao rather
than in the application database.

[y/Y] Local     OpenBao runs on this host. It is installed as
                a service, initialised, and unsealed
                automatically at boot by a root-owned hook.
                The unseal key is stored at
                /etc/ssldeploy/unseal.key (root, 0400) and
                must NEVER be included in a backup that also
                contains /var/lib/openbao - doing so removes
                the benefit of encryption at rest entirely.

[n/N] Remote    OpenBao runs on another machine. No service is
                installed here. Recommended where available:
                a reboot of THIS host cannot then stall
                renewal. Note that ssldeploy holds no unseal
                key for a remote vault - a reboot of the VAULT
                host stalls renewal until its own operator
                unseals it.

=========================================================

EOF

confirm_continue -y \
    -startmsg="Do you want to run OpenBao on this host?" \
    -endmsg="OpenBao configuration complete." \
    on_yes="openbao_local_installation || exit 1" \
    on_no="openbao_remote_installation || exit 1"

cat << EOF

${RED}=========================================================${NC}
${RED}WARNING${NC}
${RED}=========================================================${NC}
${RED}At the end of this process, this machine will hold${NC}
${RED}credentials that allow to modify your DNS zone files.${NC}
${RED}This system is meant for management networks and not for${NC}
${RED}EDGE devices or to be stored within user perimeters.${NC}
${RED}=========================================================${NC}

Requirements:
1) This machine needs access to the internet to validate your certificate request.
2) You local DNS server 
2) You will subsequently need credentials to access the servers you want to deploy certificates on.
3) It will as first stept request a certificate for this server itself to offer the management web interface.
EOF

confirm_continue -y \
    -startmsg="Do you want to proceed with setting up the credentials for this host certificate?" \
    -endmsg="Your host certificate has been set up." \
    on_no="'You have declined the host certificate setup, the installation is cancelled.'; exit 1" \
    on_yes="host_certificate_request"

# ==========================================
# Choice of O/S and Package Manager to install requirements
# ==========================================
cat << "EOF"
The script supports following operating systems: 
RHEL 
Ubuntu 26.04 LTS
Debian 10 Extended Update Support (EUS)

Other O/S might work, but are not actively supported.
If you decide to use a different O/S, please install
the application directly from source. 
EOF

# Overwrite current distro variables
# Load os-release
if [ -f /etc/os-release ]; then
    . /etc/os-release
elif [ -f /usr/lib/os-release ]; then
    . /usr/lib/os-release
else
    echo "ERROR: os-release not found"
    exit 1
fi

distro="$ID"
distro_version="$VERSION_ID"

echo "Detected: $distro $distro_version"

# Version comparison helper (uses sort -V for portability)
ver_ge() {
    # returns 0 if $1 >= $2
    [ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -n1)" = "$2" ]
}

case "$distro" in
    rhel)
        req="$RHEL_REQ_VERSION_ID"
        ;;
    ubuntu)
        req="$UBUNTU_REQ_VERSION_ID"
        ;;
    debian)
        req="$DEBIAN_REQ_VERSION_ID"
        ;;
    *)
        echo "ERROR: Unsupported distro: $distro"
        exit 1
        ;;
esac

if ! ver_ge "$distro_version" "$req"; then
    echo "ERROR: $distro requires version >= $req (found $distro_version)"
    exit 1
fi

echo "Version requirement satisfied"

# ==========================================
# Prepare DB
# ==========================================
if [ ! -f ssldeploy.db ]; then
    echo "Creating database..."
    touch ssldeploy.db
    echo "Database created."
else
    echo "Database already exists. Making Backup before migration."
    mkdir -p backup
    cp ../ssldeploy.db "../backup/ssldeploy_$(date +%Y%m%d_%H%M%S).db"
fi